<?php
return array(
	"host"=>"smtp.laposte.net",
	"port"=>587,
	"auth"=>true,
	"user"=>"allezlesbleusQCM@laposte.net",
	"password"=>"*********",
	"protocol"=>"smtp",
	"CharSet"=>"utf-8",
	"ns"=>"mail",
	"SMTPOptions"=>array(
			"ssl"=>array(
					"verify_peer"=>false,
					"verify_peer_name"=>false,
					"allow_self_signed"=>true
					)
			),
	"from"=>"allezlesbleusQCM@laposte.net"
	);